import fs from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
import {analyze,refreshTriage} from '../lib/engine.mjs';
import {makePDF} from '../lib/pdf.mjs';
import {DEMOS} from '../data/knowledge.mjs';
import samples from './samples.mjs';
const results=[];for(const s of samples){const r=await analyze(s);results.push({id:s.id,language:s.lang,expected:s.type,actual:r.scam_type,correct:r.scam_type===s.type,score:r.score,verdict:r.verdict,tool_events:r.trace.filter(t=>t.step==='Tools'&&t.status!=='running').length,failed_tools:r.trace.filter(t=>t.step==='Tools'&&t.status==='failed').length,unverified_findings:r.evidence.filter(e=>['unverified','failed'].includes(e.status)).length});}
const durations=[];let last;for(let i=0;i<5;i++){const start=performance.now();last=await analyze({text:DEMOS[0].text,lang:'hi',answers:{paid:true,amount:5000,bank:'SBI'}});last.approved_at=new Date().toISOString();last.status='approved';await makePDF(last);durations.push(performance.now()-start);}
const report={generated_at:new Date().toISOString(),dataset:'25 synthetic authored regression fixtures; not real victim messages',provider:'No AI or Safe Browsing key',taxonomy_correct:results.filter(r=>r.correct).length,samples:results.length,by_language:Object.fromEntries(['en','hi','mr'].map(lang=>[lang,{correct:results.filter(r=>r.language===lang&&r.correct).length,total:results.filter(r=>r.language===lang).length}])),pack_timings_ms:durations,median_pack_ms:[...durations].sort((a,b)=>a-b)[2],results,limitations:['No real-world classification accuracy claim','OCR and configured AI calls not evaluated','Reserved domains skip registry lookup','Tool completion does not establish verification']};
await fs.mkdir('output',{recursive:true});await fs.writeFile('output/evaluation.json',JSON.stringify(report,null,2));await fs.writeFile('output/demo-case.json',JSON.stringify(last,null,2));await fs.writeFile('output/demo-evidence-hi.pdf',await makePDF(last));const mr=refreshTriage({...last,lang:'mr'},{paid:false});mr.approved_at=new Date().toISOString();await fs.writeFile('output/demo-evidence-mr.pdf',await makePDF(mr));console.log(JSON.stringify({...report,results:undefined},null,2));
