import { env } from 'cloudflare:workers';
import {signAudit,sha256} from './security.mjs';
export function binding(): D1Database {const db=(env as unknown as {DB?:D1Database}).DB;if(!db)throw Object.assign(new Error('Case storage is unavailable.'),{status:503});return db;}
export async function saveCase(result:any,owner:string){const before=await getCase(result.id,owner);const event=await mutationIntent(result.id,owner,before,result);await binding().prepare('INSERT INTO cases (id, created_at, updated_at, status, lang, result, owner_id) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET updated_at=excluded.updated_at, status=excluded.status, lang=excluded.lang, result=excluded.result WHERE cases.owner_id=excluded.owner_id').bind(result.id,result.created_at,result.updated_at,result.status,result.lang,JSON.stringify(result),owner).run();await audit({...event,phase:'mutation-completed'},(env as any).SCAMSHIELD_AUDIT_KEY);}
export async function getCase(id:string,owner:string){const row=await binding().prepare('SELECT result FROM cases WHERE id=? AND owner_id=?').bind(id,owner).first<{result:string}>();return row?JSON.parse(row.result):null;}
export async function listCases(owner:string){const rows=await binding().prepare('SELECT id, created_at, status, lang, result FROM cases WHERE owner_id=? ORDER BY created_at DESC LIMIT 50').bind(owner).all<{id:string,created_at:string,status:string,lang:string,result:string}>();return rows.results.map(r=>{const d=JSON.parse(r.result);return {id:r.id,created_at:r.created_at,status:r.status,lang:r.lang,verdict:d.verdict,score:d.score,scam_title:d.scam_title,branch:d.branch,amount_lost:d.amount_lost};});}
export async function lookupIntel(hash:string){const row=await binding().prepare('SELECT report_count FROM intel WHERE indicator_hash=?').bind(hash).first<{report_count:number}>();return row?.report_count||0;}
export async function approveCase(id:string,drafts:any,owner:string){
 const db=binding(); const result=await getCase(id,owner);if(!result)return null;
 if(result.approved_at)return result;
 result.drafts=drafts;result.approved_at=new Date().toISOString();result.updated_at=result.approved_at;result.status='approved';
 const before=await getCase(id,owner);const event=await mutationIntent(id,owner,before,result);
 const statements=result.entities.map((e:any)=>db.prepare("INSERT INTO intel (indicator_hash,kind,report_count,first_seen,last_seen) SELECT ?,?,1,?,? WHERE EXISTS (SELECT 1 FROM cases WHERE id=? AND owner_id=? AND status='draft') ON CONFLICT(indicator_hash) DO UPDATE SET report_count=report_count+1,last_seen=excluded.last_seen").bind(e.value_hash,e.kind,result.approved_at,result.approved_at,id,owner));
 statements.push(db.prepare("UPDATE cases SET result=?,status='approved',updated_at=? WHERE id=? AND owner_id=? AND status='draft'").bind(JSON.stringify(result),result.updated_at,id,owner));await db.batch(statements);await audit({...event,phase:'mutation-completed'},(env as any).SCAMSHIELD_AUDIT_KEY);return getCase(id,owner);
}
export async function deleteCase(id:string,owner:string){const before=await getCase(id,owner);if(!before)return;const event=await mutationIntent(id,owner,before,null);await binding().prepare('DELETE FROM cases WHERE id=? AND owner_id=?').bind(id,owner).run();await audit({...event,phase:'mutation-completed'},(env as any).SCAMSHIELD_AUDIT_KEY);}
export async function quota(owner:string,write:boolean){const db=binding();const window=Math.floor(Date.now()/60000);const bucket=(write?'write:':'read:')+owner;const row=await db.prepare('INSERT INTO rate_limits(bucket,window,count) VALUES(?,?,1) ON CONFLICT(bucket,window) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,window).first<{count:number}>();await db.prepare('DELETE FROM rate_limits WHERE window<?').bind(window-2).run();if(!row||row.count>(write?12:60))throw Object.assign(new Error('Rate limit exceeded. Try again in a minute.'),{status:429});}
export async function audit(event:any,key:string){const db=binding();const body=JSON.stringify(event);for(let attempt=0;attempt<10;attempt++){const last=await db.prepare('SELECT digest FROM audit_events ORDER BY seq DESC LIMIT 1').first<{digest:string}>();const previous=last?.digest||'0'.repeat(64);const digest=await signAudit(key,previous,body);const r=await db.prepare("INSERT INTO audit_events(body,previous,digest) SELECT ?,?,? WHERE COALESCE((SELECT digest FROM audit_events ORDER BY seq DESC LIMIT 1),?)=?").bind(body,previous,digest,'0'.repeat(64),previous).run();if(r.meta.changes===1)return digest;}throw Object.assign(new Error('Audit service busy. Retry later.'),{status:503});}

async function mutationIntent(id:string,owner:string,before:any,after:any){const event={time:new Date().toISOString(),actor:owner,operation:'case-change',resource_hash:await sha256(id),before_hash:before?await sha256(JSON.stringify(before)):null,after_hash:after?await sha256(JSON.stringify(after)):null};await audit({...event,phase:'mutation-intent'},(env as any).SCAMSHIELD_AUDIT_KEY);return event;}
